### ISSUE TITLE
Update PyMC3 logo to PyMC

### ISSUE THREAD

**Issue by martinacantaro** [pymc-devs/pymcon#111]
The top left of the page still displays the old PyMC3 logo

**Comment by OriolAbril** [comment]
comes from here if someone wants to make a PR: https://github.com/pymc-devs/pymcon/tree/gh-pages/css/2017_style/img/logos

**Comment by BhaswatiRoy** [comment]
We can fix the logo link in the _config.yml file and add the new pymc logo in the logos folder too!

![image](https://user-images.githubusercontent.com/78029145/212464643-daf7f35e-c1e4-4252-9474-c2a48235b7d1.png)
![image](https://user-images.githubusercontent.com/78029145/212464666-aee938ed-3539-4849-91da-4b644e0d8ed4.png)

I can work on this issue

**Comment by cluhmann** [comment]
Looks good to me @BhaswatiRoy .  If you want to open a PR to make the relevant changes, please feel free to to do!

**Comment by BhaswatiRoy** [comment]
Hello @cluhmann 
I made the required changes and submitted a pr
Do please let me know if I need to make any changes!

**Comment by cluhmann** [comment]
Thanks so much for your contribution @BhaswatiRoy ! Please let us know if you need any help finding something else and/or claiming another open issue.  We're always happy to help.

**Comment by BhaswatiRoy** [comment]
Thanks @cluhmann !
