### ISSUE TITLE
Get in touch with us Rasul

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymcon#68]
@rrkarim your talk has been accepted to pymcon but you haven't replied back to our emails! Please get back to us! We need your deets

**Comment by rrkarim** [comment]
yeap, I'm really sorry, I will reply asap.

[EDIT] Sorry, I wasn't too sure that I would be able to complete everything before the deadline.

**Comment by OriolAbril** [comment]
Thanks! closing this then
